import groovy.json.JsonSlurper

plugins {
    id "idea"
    id "groovy"
    id "com.energizedwork.webdriver-binaries" version "1.4"
    id "com.energizedwork.idea-base" version "1.4"
}

def defaultDrivers = ["chrome", "firefox"]
def bsDrivers = []

// Define the location of your JSON file
def jsonFile = file('src/test/groovy/extraSettings.json')
if (jsonFile.exists() && jsonFile.text) {
    // Parse the JSON file
    def jsonSlurper = new JsonSlurper()
    def jsonContent = jsonSlurper.parse(jsonFile)
    // Extract BS project attributes from the JSON file
    if (jsonContent?.browserstack?.caps) {
        bsDrivers = jsonContent.browserstack.caps.collect { it.project }
    }
}

// Merge default drivers with project drivers from the JSON file
def drivers = defaultDrivers + bsDrivers

ext {
    // The drivers we want to use
    drivers = drivers
    ext {
        groovyVersion = '2.4.12'
        gebVersion = '2.2'
        seleniumVersion = '3.6.0'
        chromeDriverVersion = '97.0.4692.71'
        geckoDriverVersion = '0.23.0'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.6'
    // If using Spock, need to depend on geb-spock
    testCompile "org.gebish:geb-spock:$gebVersion"
    testCompile("org.spockframework:spock-core:1.1-groovy-2.4") {
        exclude group: "org.codehaus.groovy"
    }
    testCompile "org.codehaus.groovy:groovy-all:$groovyVersion"

    // If using JUnit, need to depend on geb-junit (3 or 4)
    testCompile "org.gebish:geb-junit4:$gebVersion"

    // Drivers
    testCompile "org.seleniumhq.selenium:selenium-chrome-driver:$seleniumVersion"
    testCompile "org.seleniumhq.selenium:selenium-firefox-driver:$seleniumVersion"
    testImplementation group: 'io.appium', name: 'java-client', version: '7.3.0'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-support', version: '3.141.59'
    
    // JSON simple for MuukReport
    implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'
     
    implementation 'com.github.javafaker:javafaker:1.0.2'

}

webdriverBinaries {
    chromedriver chromeDriverVersion
    geckodriver geckoDriverVersion
}

drivers.each { driver ->
    task "${driver}Test"(type: Test) {
        group JavaBasePlugin.VERIFICATION_GROUP

        outputs.upToDateWhen { false }  // Always run tests

        systemProperty "geb.build.reportsDir", reporting.file("geb/$name")
        systemProperty "geb.env", driver
    }
}

test {
    dependsOn drivers.collect { tasks["${it}Test"] }
    enabled = false
}

tasks.withType(Test) {
    maxHeapSize = "1g"
    jvmArgs '-XX:MaxMetaspaceSize=128m'
    testLogging {
        exceptionFormat = 'full'
    }
}

tasks.withType(GroovyCompile) {
    groovyOptions.forkOptions.memoryMaximumSize = '256m'
}
