#!/bin/bash
#Changing the executor permissions
sudo chmod 777 /home/ubuntu/projects/executor

#Setting the cloud key
#The cloud key it's located in a external config.json file
if [[ -f "/home/ubuntu/config.json" ]]; then
  #Changing portal route to the proper one in the config file
  muuktestRoute=$(cat /home/ubuntu/config.json  | jq -r '.muuktestRoute')
  sudo sed -i "s/portal.muuktest.com/'$muuktestRoute'" /home/ubuntu/projects/executor/mkcli.py

  #Adding the cloudKey in the mkcloud.py file
  cloudKey=$(cat /home/ubuntu/config.json  | jq -r '.cloudKey')
  sudo sed -i '$ a def getCloudKey():' /home/ubuntu/projects/executor/mkcloud.py
  sudo sed -i "$ a  \ \ return('$cloudKey')" /home/ubuntu/projects/executor/mkcloud.py
fi