#!/bin/bash
#Changing the executor permissions
sudo chmod 777 /home/ubuntu/projects/executor

#Setting the cloud key
#The cloud key it's located in a external env.json file
if [[ -f "/home/ubuntu/config.json" ]]; then
  cloudKey=$(cat /home/ubuntu/config.json  | jq -r '.cloudKey')
  sudo sed -i '$ a def getCloudKey():' /home/ubuntu/projects/executor/mkcloud.py
  sudo sed -i "$ a  \ \ return('$cloudKey')" /home/ubuntu/projects/executor/mkcloud.py
fi