#!/bin/bash
#Installing Pip3
sudo apt -y install python3-pip
#Installing BeautifulSoup4
sudo pip3 install BeautifulSoup4
#sudo pip3 install bs4
#Installing xvfb
sudo apt -y install xvfb
#Installing firefox
sudo apt -y install firefox
#Installing ffmpeg
sudo apt -y install ffmpeg
#Installing request
pip3 install request
#Installing jq to read json files
sudo apt -y install jq
#Installing lxml
sudo pip3 install lxml
#Installing Google 114
wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.198-1_amd64.deb
sudo dpkg -i google-chrome-stable_114.0.5735.198-1_amd64.deb
sudo rm google-chrome-stable_114.0.5735.198-1_amd64.deb