#!/bin/bash
#Installing Pip3
sudo apt -y install python3-pip
#Installing BeautifulSoup4
sudo pip3 install BeautifulSoup4
#sudo pip3 install bs4
#Installing xvfb
sudo apt -y install xvfb
#Installing firefox
sudo apt -y install firefox
#Installing ffmpeg
sudo apt -y install ffmpeg
#Installing request
pip3 install request
#Installing jq to read json files
sudo apt -y install jq